# Bandit configuration file
# Focus only on application code

exclude_dirs:
  - '*/venv'
  - '*/tests'
  - 'htmlcov'
  - '*/migrations'
  - '*.egg-info'
  - '__pycache__'
  - '.git'
  - '.github'
  - '.vscode'
  - '*/seed_data'

# Only scan Python files in app directory
include:
  - 'flask_app/src/main/app/*.py'
  - 'flask_app/src/main/config.py'

# Skip common false positives
skips:
  - B101  # assert statements